### ISSUE TITLE
Issue with caching Gatsby .cache folder

### ISSUE THREAD

**Issue by steverandy** [aws-amplify/amplify-console#256]
**Describe the bug**
Getting a build error if caching is enabled for `.cache` folder in a Gatsby project.

**To Reproduce**
1. Add `.cache` to amplify.yml
```
cache:
    paths:
      - 'node_modules/**/*'
      - '.cache/**/*'
      - 'public/static/**/*'
```
2. Build failed with error:
`Failed to process image /codebuild/output/src284496123/src/project/.cache/gatsby-source-filesystem/2864d13ac3b594d2252bb53b755dec5e/b49bb9721c3ae1f55a9e7ec02caddb02567d5477_file_name.png Input file is missing`

**Expected behavior**
There should not be a missing file in `.cache` folder.

**Additional context**
https://stackoverflow.com/questions/57094634/change-cache-folder-files-paths-from-absolute-to-relative-is-it-possible

**Comment by Joycehao19** [comment]
@steverandy Can you try delete the app and add it again?

**Comment by steverandy** [comment]
@Joycehao19 we cannot delete the app because we have a production environment already deployed. Is it a necessary step to delete the app to fix the issue?

**Comment by swaminator** [comment]
@stevenrandy you definitely do not need to delete the app. We'll look into this further and get back to you soon.

**Comment by steverandy** [comment]
@swaminator is there any update on this? Thanks.

**Comment by tinder-kyleboss** [comment]
I am running into the same issue with a standard CodeBuild/CodePipeline set-up.

**Comment by tinder-kyleboss** [comment]
I would like to point out that I believe this is related to the issue @sirichards is facing here: https://github.com/gatsbyjs/gatsby/issues/17990

It looks like the issue here is that Gatsby uses the absolute path of the previous build to architect `.cache`. Unfortunately, the absolute path will change with every build.

**Comment by kyleboss** [comment]
I've been hacking away at this for several days and finally found a work-around (not a solution). 

*buildspec.yml*
```
version: 0.2

phases:
  pre_build:
    commands:
      - mkdir -p /build-directory
      - cp -a ${CODEBUILD_SRC_DIR}/. /build-directory
      - cd /build-directory
      - yarn
  build:
    commands:
      - cd /build-directory
      - gatsby build
  post_build:
    commands:
      - cd /build-directory
      - cp -a /build-directory/. ${CODEBUILD_SRC_DIR}
cache:
  paths:
    - 'node_modules/**/*'
    - 'public/**/*'
    - '.cache/**/*'
```

Gatsby assumes that the absolute path to `.cache` is consistent between builds. This is not very compatible with CodeBuild since the build directory changes for each build. Because of this, Gatsby isn't able to locate the cached files and throws an error.

For this reason, creating a consistent path and bringing the artifacts there will solve the issue. When the build is done, be sure to bring the new artifacts to the `CODEBUILD_SRC_DIR` so that they can be cached for next time!

**Comment by steverandy** [comment]
@ganipcanot is this issue fixed now?

**Comment by ganipcanot** [comment]
@steverandy 

- I closed it based on age
- There is a workaround for now
- We are aware of users having issues with gatsby sites and are prioritizing that work

If you want to re-open for tracking purposes feel free.

**Comment by alacret** [comment]
I can confirm that this setting doesn't work, failing with:

```
2021-01-04T02:08:24.521Z [WARNING]: !TypeError: Cannot read property 'cache' of undefined
```

in the building phase

**Comment by chrisddonldson** [comment]
Any updates on this? I am having a very similar issue. No matter what the config I can't get Gatsby to use the cached pages.

**Comment by alana314** [comment]
We are having this same error and the above buildspec doesn't fix it. This is for a local cached build on CodeBuild? The error we get are flavors of:
```Can't resolve './../../../src/pages/index.js' in '/codebuild/local-cache/custom/f45810edd0910857.../.cache/_this_is_virtual_fs_path_/$virtual'```
@kyleboss when you say "When the build is done, be sure to bring the new artifacts to the CODEBUILD_SRC_DIR so that they can be cached for next time," isn't that what `cp -a /build-directory/. ${CODEBUILD_SRC_DIR}` is doing? We are using gatsby-plugin-s3 to deploy and not CodeBuild's artifacts, not sure if that matters.

**Comment by alana314** [comment]
I was getting the above errors because .cache is an alias in codebuild, and the JS was running from the target of the alias. Instead I copied the contents of our three cached folders and then copied them back. I had to use if statements for copy in case the cache folders didn't exist (very first time building). I also had issues copying the whole build-directory folder if the subfolders existed, so I only copied the three folders we're caching. Deployment still takes an extra 5 minutes because of how large our site is, next I want to look into if there's a way to only deploy the modified files.
Here is our buildspec file:
```
version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo prepare env. Ensure latest version of node is available.
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get install -y make apt-transport-https
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get install -y yarn
      - yarn global add gatsby-cli
      - echo done with prepare env.
  pre_build:
    commands:
      - echo prebuild site using yarn
      - echo "Checking cache"
      - ls .cache/
      - mkdir -p /build-directory
      - cp -a ${CODEBUILD_SRC_DIR}/. /build-directory
      - rm -f /build-directory/.cache
      - rm -f /build-directory/node_modules
      - rm -f /build-directory/public
      - mkdir /build-directory/.cache
      - mkdir /build-directory/node_modules
      - mkdir /build-directory/public
      - |
        if [ -d ${CODEBUILD_SRC_DIR}/.cache/. ]; then 
        cp -a ${CODEBUILD_SRC_DIR}/.cache/. /build-directory/.cache/
        else
        echo ".cache not found"
        fi
      - |
        if [ -d ${CODEBUILD_SRC_DIR}/public/. ]; then 
        cp -a ${CODEBUILD_SRC_DIR}/public/. /build-directory/public/
        else
        echo "public not found"
        fi
      - |
        if [ -d ${CODEBUILD_SRC_DIR}/node_modules/. ]; then 
        cp -a ${CODEBUILD_SRC_DIR}/node_modules/. /build-directory/node_modules/
        else
        echo "node_modules not found"
        fi
      - cd /build-directory
      - yarn
  build:
    commands:
      - echo build site using yarn
      - cd /build-directory
      - yarn build
      - echo done building
  post_build:
    commands:
      - cd /build-directory
      - echo "Saving cache"
      - cp -a /build-directory/.cache/. ${CODEBUILD_SRC_DIR}/.cache/
      - cp -a /build-directory/public/. ${CODEBUILD_SRC_DIR}/public/
      - cp -a /build-directory/node_modules/. ${CODEBUILD_SRC_DIR}/node_modules/
      - echo syncing to s3 and cloudfront
      - yarn deploy
      - echo after sync to S3
  cache:
    paths:
      - 'node_modules/'
      - 'public/'
      - '.cache/'
```

**Comment by alejoar** [comment]
@steverandy  do you mind reopening this issue? 

This is not fixed.
