### ISSUE TITLE
Pull-Request Previews Check does not return result. Stuck in Queue

### ISSUE THREAD

**Issue by thedmeyer** [aws-amplify/amplify-console#367]
**Please fill out all fields before submitting**

1. **Issue Description**

When a PR is opened, the Pull-Request Preview check runs, but intermittently refuses to return a result to GitHub. The status gets stuck as "In Queue" on Github. When checking the amplify console, the PR preview did finish building, but Github was never notified of this.

See below.

<img width="452" alt="amplifystuck" src="https://user-images.githubusercontent.com/2959172/72557109-ec3c3b00-3854-11ea-8ae5-22da7e1cf7e0.png">

1. **Detailed Steps To Reproduce**

- Open a PR with new changes.
- Wait for changes to build on amplify.
- (Result never returns completed status to Github)

**Comment by thedmeyer** [comment]
This issue is intermittent. It occurs on some PRs or after new pushed changes.

**Comment by cslogan-red** [comment]
Hi @thedmeyer , I haven't been able to repro this with some quick repeated testing however it's still possible this is an issue on our side or with the Checks API, we'll have to investigate this one a little further.

**Comment by ganipcanot** [comment]
Not able to reproduce it etiher - please open a new issue if this continues.

**Comment by jfcsantos** [comment]
Hit there @cslogan-red, @ganipcanot I am getting the same issue every other Pull Request. Is there any input/progress on this at all?

**Comment by galamiram-walnut** [comment]
@ganipcanot @cslogan-red I'm getting the same results... PR checks are stuck in pending
![Screen Shot 2021-04-27 at 10 18 11](https://user-images.githubusercontent.com/79851970/116201183-e57fc180-a741-11eb-8976-491bc3af1377.png)

**Comment by tomasechague** [comment]
i have the same problem as @galamiram-walnut . Amplify checking commit since 16 hours ago

**Comment by cslogan-red** [comment]
@galamiram-walnut @tomasechague can you post your app Id's and regions? Our customer on-call this week will take a look, a couple of scenarios where this may happen that are app-dependent.

**Comment by galamiram-walnut** [comment]
@cslogan-red App ID: `dchqkv55e03yh` Region: `us-west-2`

**Comment by kegorgas** [comment]
> can you post your app Id's and regions? Our customer on-call this week will take a look, **a couple of scenarios where this may happen that are app-dependent.**

@cslogan-red Would it be possible to get a list of those scenarios that could cause this? We are running into this as well and I would like to go through them to see if I can change anything on our end to rectify this (assuming that it is something that we can change in our app settings from our end).

**Comment by giioohbernini** [comment]
The same problem here :/ 

![image](https://user-images.githubusercontent.com/13969702/142634635-a0b4acf1-d24f-4aa0-8ff8-b44441e36df7.png)

**Comment by ciceropablo** [comment]
Any news? I have the same problem here, but it is intermittent.

**Comment by guilhermepontes** [comment]
That's a pretty annoying one, happening constantly.

**Comment by ganipcanot** [comment]
For anyone that is having this issue could you share details such as:

`appId` or `appArn`
`branchArn`

The time or rough time when the issue happened - this will help is dig into it further to figure out where things are getting stuck.

**Comment by MarvineGothic** [comment]
it also happens for us. This Preview stuck on a first build if it failed. Then I fixed the code and re-run the build. So the last preview build is successful, but this one in the PR is still 'in progress' and the link points to the first build.

**Comment by MarvineGothic** [comment]
<img width="1352" alt="Screenshot 2022-01-28 at 20 55 00" src="https://user-images.githubusercontent.com/29262588/151612881-f5bbf8bb-a2f8-431f-a535-a58499a8665e.png">
<img width="1371" alt="Screenshot 2022-01-28 at 20 55 14" src="https://user-images.githubusercontent.com/29262588/151612883-00f2f70a-5308-46b0-b14d-344c236c122f.png">

**Comment by utilscottquested** [comment]
<img width="838" alt="Screenshot 2022-02-01 at 19 41 59" src="https://user-images.githubusercontent.com/97965067/152039449-a8059af2-19d8-4119-8b3f-ea6eef3aa356.png">
Happening every other PR now. ETA on a fix?

**Comment by aimeeu** [comment]
I also experience this problem when the build fails. AWS Amplify doesn't notify GitHub of the failure.

I am evaluating AWS Amplify as a host for my company's static docs site, which uses Hugo. I deliberately created a commit that I know will not build, pushed to existing PR, the build fails in Amplify in under 2 minutes, but the GH PR doesn't reflect that failure - stuck in "In progress - This check has started" 
Thursday 10 February 2022, 11:10 am US CST
appArn: arn:aws:amplify:us-east-2:025179128306:apps/d3gxyt39wk36i7

I don't see a branchArn. The branch is PR-2

![image](https://user-images.githubusercontent.com/26799583/153461757-c6ab0ce8-0282-4571-94eb-1d5f4a9aa32a.png)

**Comment by clichedmoog** [comment]
I want to add to @aimeeu 's comment
When the preview build failed once, even if I click the "Redeploy this version" button on PR's AWS Amplify's web console.
AWS Amplify does not notify GitHub, so the PR's checks are not updated and are still stuck in the "In progress" state.

![Screen Shot 2022-03-11 at 11 23 53 AM](https://user-images.githubusercontent.com/1225082/157790276-6dc59d45-8666-4b49-9e4a-5ba7d7fee244.png)
![Screen Shot 2022-03-11 at 11 24 14 AM](https://user-images.githubusercontent.com/1225082/157790268-0a4efc0b-3175-4212-a98e-bd1f0a8e9847.png)

**Comment by neekey** [comment]
@clichedmoog same experience for me. Except all the other amazing feature Amplify provides, the build log / build status part of the integration with Github part is very frustrating

**Comment by colemars** [comment]
In my case, the build has succeeded, but github still shows in progress.

**Comment by DanielJSottile** [comment]
For my team, this is still an issue.  The checks are not consistent either, as some will pass/fail, while others will stall indefinitely. Build/deployment succeeds but we can't use the check right now to verify PR's

**Comment by ganipcanot** [comment]
We recently released a fix where Failed builds would not correctly update the GH status check.

There is a separate scenario where if you open a pull request then add some changes on top of it - this will queue up another build.  We had a bug in that scenario where the GH status check would get "hung" i.e. stuck in progress.  That fix has been merged but not yet deployed.

**Comment by ag14774** [comment]
This still happens for me. If you open a PR and merge before the build for the PR preview is done, the preview is correctly destroyed on AWS but on github it stays pending forever @ganipcanot

**Comment by c-kle** [comment]
Exact same scenario as @ag14774, we have a couple of check_runs that have been pending for days/weeks now and there is no way to cancel them ?
