### ISSUE TITLE
Naked domain not working

### ISSUE THREAD

**Issue by piplani** [aws-amplify/amplify-console#977]
Hi,
I deployed my react app and connected it to the custom domain. 
If I open https://www.brijwasibakery.com it works.
If I open www.brijwasibakery.com it works.
If I open https://brijwasibakery.com it doesn't work.

Basically I am facing problems with the naked domain.
I have set up a redirect in the settings but it is not working.(photo attached)

![image](https://user-images.githubusercontent.com/24450586/90490320-1ee84200-e15c-11ea-88d2-f84a0d834734.png)

Please help.

**Comment by cslogan-red** [comment]
Hi @piplani , all three are now resolving so it appears you've figured this out, let us know if you have any further questions

**Comment by dineshsonachalam** [comment]
Hi @piplani , 

I'm also facing the same problem. Please let me know how did you solve this issue?

**Background story:**

I deployed a React application by using the Amplify console. Then I configured a custom domain in the Domain Management section in the Amplify console.  

Then I added the redirection rules to redirect my **https://mycustomdomain.com** to **https://www.mycustomdomain.com** in the Rewrites and Redirection section in the Amplify console.
```
[
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    },
    {
        "source": "https://mycustomdomain.com",
        "target": "https://www.mycustomdomain.com",
        "status": "302",
        "condition": null
    }
]f
```

- Here www.mycustomdomain.com is available on the internet.
- when I hit https://mycustomdomain.com the redirect to https://www.mycustomdomain.com is not happening. So my website is not available on the internet. 

**Steps to reproduce this issue:**
1. Create a react app and deploy it to amplify.
2. Set up a custom domain for your amplify app.
3. Add the following redirection rules in the Rewrites and Redirection section.
```
[
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    },
    {
        "source": "https://mycustomdomain.com",
        "target": "https://www.mycustomdomain.com",
        "status": "302",
        "condition": null
    }
]f
```

I feel like the redirection rules management is not properly handled by the Amplify console and it's a bug related to the Rewrite and Redirection management in the Amplify console.

Please let me know how to resolve this issue and track it as a bug if it's a valid bug. Also, let me know about any alternatives if they are available.
i
cc: @cslogan-red, @swaminator , @ericclemmons , @hyandell , @litwicki

**Comment by dineshsonachalam** [comment]
I was able to resolve this issue using the following rewrites and redirection rule. 
```
[
    {
        "source": "https://freshworks.com.com",
        "target": "https://www.freshworks.com.com",
        "status": "302",
        "condition": null
    },
    {
        "source": "/<*>",
        "target": "/index.html",
        "status": "404-200",
        "condition": null
    },
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]
```

**Comment by timothymarois** [comment]
Slightly old, but based on this, there is no way to have to amplify run on the root domain is there? This is a deal-breaker for me, I do not use or ever want to use www as the website endpoint.

**Comment by ferdingler** [comment]
@timothymarois. We do support root/apex domains on Amplify as long as your DNS provider supports adding ANAME records. An ANAME record is like a CNAME record, but at the root level. It points the root of your domain to an FQDN (Fully Qualified Domain Name) like d1m7bkiki6tdw1.cloudfront.net which then points to an IP address. 

```
example.com      ANAME      d11m7wekbwbvek.cloudfront.net
```

If your DNS provider doesn't support ANAME records, you could [make Amazon Route53 the DNS service for your domain](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/MigratingDNS.html).

**Comment by jacobsapps** [comment]
I'm bumping this because I have the same problem and the proposed solutions didn't work. 

Questions: 
- What am I supposed to have in domain management? I currently have https://www.domain.com and www.domain.com both pointing at my main branch without redirects. When I try to add the redirect to the naked domain alone, it still doesn't work.
- Is it supposed to take a while for the redirect rules to apply because of DNS? Would waiting solve the problem?

**Comment by TonyKnibb-MakaraHealth** [comment]
> d11m7wekbwbvek.cloudfront.net

I switched my domain to Route53 because my registrar did not support ANAME, exactly as AWS instructed. 

But nothing I've tried in Route53 works either. 

It also doesn't clearly indicate how to create an ANAME. I've tried using CNAME with alias checked on, and also A and AAAA with alias checked on. 

Nothing seems to work.

**Comment by rennehir** [comment]
> I would like to clarify for people who don't know:
>
> This means creating an A record, and checking the "alias" toggle, with no extension added to the start of the domain.
>
> Select "Alias to CloudFront distribution" and paste in your link. E.g., xxxxxxx.cloudfront.net

And to clarify a bit more:

Even though the AWS console seems like to search for the distribution and expecting you to choose from a list, you can just paste the link and create the record.
